### ISSUE TITLE
Error I try to run my code 

### ISSUE THREAD

**Issue by natsu2912** [hugsy/cemu#48]
This is the log in terminal when I press the button "Run all code".
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/cemu/ui/main.py", line 168, in runCode
    self.run()
  File "/usr/local/lib/python3.6/dist-packages/cemu/ui/main.py", line 174, in run
    if not self.loadContext():
  File "/usr/local/lib/python3.6/dist-packages/cemu/ui/main.py", line 135, in loadContext
    if not self.emu.compile_code(code):
  File "/usr/local/lib/python3.6/dist-packages/cemu/emulator.py", line 170, in compile_code
    self.code, self.num_insns = assemble(code, self.parent.arch)
  File "/usr/local/lib/python3.6/dist-packages/cemu/utils.py", line 149, in assemble
    arch, mode, endian = get_arch_mode("keystone", mode)
  File "/usr/local/lib/python3.6/dist-packages/cemu/utils.py", line 67, in get_arch_mode
    if lib=="keystone":     arch, mode, endian = keystone.KS_ARCH_ARM, keystone.KS_MODE_ARM, keystone.KS_MODE_LITTLE_ENDIAN
AttributeError: module 'keystone' has no attribute 'KS_ARCH_ARM'

**Comment by Azurewyl** [comment]
same but KS_ARCH_X86

**Comment by hugsy** [comment]
Use this script to install the correct versions of capstone, keystone and unicorn

https://github.com/hugsy/stuff/blob/master/update-trinity.sh
