### ISSUE TITLE
Compile help

### ISSUE THREAD

**Issue by DigiAngel** [hugsy/cemu#6]
Can we get some guidance on installing the deps?  I've git pulled capstone, keystone, unicorn, and complied and installed all.  I still get:
~~~
Traceback (most recent call last):
  File "main.py", line 18, in <module>
    from cemu.core import Cemu
  File "/home/jlay/build/cemu/cemu/core.py", line 9, in <module>
    import unicorn
ImportError: No module named unicorn
~~~
How do you get the python bindings?

**Comment by DigiAngel** [comment]
Yea helps to look in EACH dir 8-\  Disregard and thanks.
