### ISSUE TITLE
module 'cemu' has no attribute 'context'

### ISSUE THREAD

**Issue by quert999** [hugsy/cemu#92]
win10 64
python3.10.6
cemu0.7
type anything will crash with log

[DEBUG] Starting in Debug Mode
[DEBUG] Creating GUI context
[DEBUG] Settings loaded from 'C:\Users\Administrator.SY-202403081812\.cemu.ini'
[SUCCESS] Loaded plugin 'C:\Users\Administrator.SY-202403081812\AppData\Local\Programs\Python\Python310\lib\site-packages\cemu\plugins\pyconsole'
[SUCCESS] Loaded plugin 'C:\Users\Administrator.SY-202403081812\AppData\Local\Programs\Python\Python310\lib\site-packages\cemu\plugins\scratchboard.py'
[DEBUG] Main window initialized
cccdskajdksajdkajs
[DEBUG] Emulator state transition: STARTING -> NOT_RUNNING
[INFO] Emulator is now NOT_RUNNING
[DEBUG] Executing 4 callbacks for state NOT_RUNNING
[DEBUG] cemu.ui.registers.method.updateGrid() return None
[DEBUG] cemu.ui.mapping.method.onNotRunningUpdateMemoryMap() return None
[DEBUG] cemu.ui.command.method.onNotRunningUpdateCommandButtons() return None
[DEBUG] cemu.ui.main.method.update_layout_not_running() return None
<module 'cemu' from 'C:\\Users\\Administrator.SY-202403081812\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\cemu\\__init__.py'>
Traceback (most recent call last):
  File "C:\Users\Administrator.SY-202403081812\AppData\Local\Programs\Python\Python310\lib\site-packages\cemu\ui\codeeditor.py", line 178, in onUpdateText
    cemu.core.context.emulator.codelines = self.getCleanContent()
  File "C:\Users\Administrator.SY-202403081812\AppData\Local\Programs\Python\Python310\lib\site-packages\cemu\ui\codeeditor.py", line 239, in getCleanContent
    lines = parse_syscalls(lines)
  File "C:\Users\Administrator.SY-202403081812\AppData\Local\Programs\Python\Python310\lib\site-packages\cemu\ui\codeeditor.py", line 210, in parse_syscalls
    syscalls = cemu.core.context.architecture.syscalls
  File "C:\Users\Administrator.SY-202403081812\AppData\Local\Programs\Python\Python310\lib\site-packages\cemu\arch\__init__.py", line 74, in syscalls
    self.__context = getattr(mod, "context")
AttributeError: module 'cemu' has no attribute 'context'

**Comment by hugsy** [comment]
Same as #87
